language: python
sudo: false
cache: pip
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy3
  - TOXENV=py27-pyflakes
  - TOXENV=py27-pep8
  - TOXENV=py27-coverage
install:
  - pip install tox
  - pip install coveralls
script:
  tox
after_success:
  coveralls --verbose
