language: python
sudo: false
cache: pip
env:
  - TOXENV=py27
  - TOXENV=py36
  - TOXENV=pypy2.7
  - TOXENV=py27-pyflakes
  - TOXENV=py27-pep8
  - TOXENV=py27-coverage
install:
  - pip install tox
  - pip install coveralls
script:
  tox
after_success:
  coveralls --verbose
